config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :carts
  
  get 'mypage/mypage'
  get 'mypage/requests_list'

  resources :orders, except: [:create, :new]
  post 'orders/placeorder' => 'orders#placeorder'
  get 'allorders' => 'orders#all'
  
  get 'cart' => 'carts#index'
  delete 'cart/:id' => 'carts#deletecart'
  post 'cart/:id' => 'carts#addcart'

 resources :boards, only: [:index] do
    resources :articles, only: [:update, :destroy, :create]
  end
  
  scope '/boards/:board_id', except: [:update, :destroy, :create] do
    resources :articles
  end
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :path => "users", :path_names => {:sign_up => "register"}
  
  devise_scope :user do
    get "/users/seller_new" =>"registrations#seller_new"
    get "/users/sign_out" =>"devise/sessions#destroy"
  end
  
  
 

  root 'wenique#index'

  get 'wenique/product'

  get 'wenique/contact'

  get 'wenique/checkout'

  get 'wenique/categories'

  
  get 'wenique/registers_new'
  
  
  get 'wenique/assign_order/new' => 'wenique#assign_order_new' #지정주문제작서 작성 화면
  
  post 'wenique/assign_order/create' => 'wenique#assign_order_create', as: 'assign_order_create'
  
  get 'wenique/assign_order/show/:id' => 'wenique#assign_order_show' #지정주문제작서 확인
  
  get 'wenique/assign_order/edit/:id' => 'wenique#assign_order_edit'
  
  patch 'wenique/assign_order/update/:id' => 'wenique#assign_order_update', as: 'assign_order_update'
  
  post 'assign_order/:id/create' => 'wenique#assign_order_comment_create', as: 'assign_order_comment_create'
  
  get 'assign_order/:id/make_price' => 'wenique#assign_order_make_price', as: 'assign_order_make_price'
  
  post 'assign_order/:id/make_price/create' => 'wenique#assign_order_make_price_create', as: 'price_create'
  
  get 'assign_order/:id/price_agree' => 'wenique#price_agree'
  
  get '/users/search' => 'wenique#user_search', as: 'search_users'
  
  get 'wenique/unassign_order'  #미지정주문제작 화면
  
  get 'wenique/handicrafts'
  
  get '/mypage/assign_order/show/:id' => 'wenique#assign_order_show'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    # attr_accessor :title, :board_id
    mount_uploader :img, ImguploaderUploader
    belongs_to :board
    
    #u_id는?
end

app/models/autority.rb
class Autority < ActiveRecord::Base
    has_many :users, dependent: :destroy
end

app/models/board.rb
class Board < ActiveRecord::Base
        has_many :articles, dependent: :destroy
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :good
    
    def goodz
        @good = Good.find(self.good_id)
        return @good
    end
    
 
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :assign_requests
    has_and_belongs_to_many :users
    has_and_belongs_to_many :unassign_requets
end

app/models/good.rb
class Good < ActiveRecord::Base
    belongs_to :assign_request
    belongs_to :unassign_request
    has_one :request_status
    has_one :portfolio
    has_many :reviews, dependent: :destroy
    has_many :order_items
    
    has_many :carts
    has_many :Users, through: :Carts
    
    has_many :itemorder
    has_many :orders, through: :goodorder    
end

app/models/goodorder.rb
class Goodorder < ActiveRecord::Base
  belongs_to :good
  belongs_to :order
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    
    has_many :goodorders, dependent: :destroy
    has_many :items, through: :goodorders
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    belongs_to :good
end

app/models/price_comfirm.rb
class PriceComfirm < ActiveRecord::Base
    # belongs_to :assign_request
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :following, class_name: "User", foreign_key: :following_id, primary_key: :id
    validates :following_id, presence: true
    belongs_to :follower, class_name: "User"
    validates :follower_id, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :good
end

app/models/seller_page.rb
class SellerPage < ActiveRecord::Base
    belongs_to :user
    
    #포트폴리오는 ?
end

app/models/status.rb
class Status < ActiveRecord::Base
    has_many :request_statues, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :categories
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :following
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  belongs_to :autority
  
  has_one :seller_page
  has_many :unassign_requests, dependent: :destroy
  has_many :assign_request_comments, dependent: :destroy

  has_many :orders, dependent: :nullify
  
  has_many :goods, through: :carts
  has_many :carts, dependent: :destroy  
  
  def following?(other_user)
    active_relationships.find_by(following_id: other_user.id)
  end
  
  def follow!(other_user)
    active_relationships.create!(following_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end
  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_board

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.where(board_id: params[:board_id])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.board_id = @board.id
    
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_path(@board, @article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to [@board, @article], notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      # @article.board_id = Board.find(params[:board_id])
      @board = Board.find(params[:board_id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :img)
    end
    
    def set_board
      @board = Board.find(params[:board_id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/articles/_form.html.erb
<%= form_for([@board, @article], :multipart => true) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, '제목' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content, '내용' %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :img, '이미지' %>
    <%= f.file_field :img %>
  </div>
  
  <div class="actions">
    <%= f.submit '글쓰기', :class => 'button' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<link rel="stylesheet" type="text/css" href="article.css">

<div class="container">
<h1>글 수정</h1>

<%= render 'form' %>

<%= link_to '글보기', [@board, @article] %> |
<%= link_to '목록', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h2><%= @board.title %></h2>
  
  <!--<table>-->
  <!--  <thead>-->
  <!--    <tr>-->
  <!--      <th>Title</th>-->
  <!--      <th>Content</th>-->
  <!--      <th colspan="3"></th>-->
  <!--    </tr>-->
  <!--  </thead>-->
  
  <!--  <tbody>-->
  <!--    <%# @articles.each do |article| %>-->
  <!--      <tr>-->
  <!--        <td>-->
  <!--          <%# unless article.img_url.nil? %>-->
  <!--          <img src="<%#= article.img_url %>" />-->
  <!--          <%# end %>-->
  <!--        </td>-->
  <!--        <td><%#= article.title %></td>-->
  <!--        <td><%#= article.content %></td>-->
  <!--        <td><%#= link_to 'Show', article_path(@board, article) %></td>-->
  <!--        <td><%#= link_to 'Edit', edit_article_path(@board, article) %></td>-->
  <!--        <td><%#= link_to 'Destroy', [@board, article] , method: :delete ,data: { confirm: 'Are you sure?' } %></td>-->
  <!--      </tr>-->
  <!--    <%# end %>-->
  <!--  </tbody>-->
  <!--</table>-->
  
  <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">제목</th>
      <% if user_signed_in? %>
        <% if current_user.authorization == '1' %>
          <th scope="col"></th>
        <% end %>
      <% end %>
    </tr>
  </thead>
    <% @i = 1 %>
    <% @articles.each do |article| %>
      <tbody>
        <tr>
          <th scope="row"><%= @i %></th>
          <td><%= link_to article.title, article_path(@board, article) %></td>
          <% if user_signed_in? %>
            <% if current_user.authorization == '1' %>
              <td>
                <%= link_to '편집', edit_article_path(@board, article) %> |
                <%= link_to '삭제', [@board, article] , method: :delete %>
              </td>
            <% end %>
          <% end %>
        </tr>
      </tbody>
      <% @i = @i + 1 %>
    <% end %>
  </table>
  <br>
  <button class="button">
  <%= link_to "#{@board.title} 글쓰기", new_article_path%>
  </button>
</div>

app/views/articles/new.html.erb
<link rel="stylesheet" type="text/css" href="article.css">

<div class="container">
<h1>글쓰기</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<link rel="stylesheet" type="text/css" href="article.css">

<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>제목</strong><br>
    <%= @article.title %>
  </p>
  
  <p>
    <strong>내용</strong><br>
    <%= @article.content %>
  </p>
  <p>
    <!--<strong>사진</strong><br>-->
    <%= image_tag("#{@article.img_url}",class:"orderimg")%>
  </p>


  <%= link_to '편집', edit_article_path(@board, @article) %> |
  <%= link_to '뒤로가기', articles_path %> |
  <%= link_to '삭제', [@board, @article] , method: :delete ,data: { confirm: 'Are you sure?' } %></td>
</div>