config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :carts
  
  get 'mypage/mypage'
  get 'mypage/requests_list'

  resources :orders, except: [:create, :new]
  post 'orders/placeorder' => 'orders#placeorder'
  get 'allorders' => 'orders#all'
  
  get 'cart' => 'carts#index'
  delete 'cart/:id' => 'carts#deletecart'
  post 'cart/:id' => 'carts#addcart'

 resources :boards, only: [:index] do
    resources :articles, only: [:update, :destroy, :create]
  end
  
  scope '/boards/:board_id', except: [:update, :destroy, :create] do
    resources :articles
  end
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :path => "users", :path_names => {:sign_up => "register"}
  
  devise_scope :user do
    get "/users/seller_new" =>"registrations#seller_new"
    get "/users/sign_out" =>"devise/sessions#destroy"
  end
  
  
 

  root 'wenique#index'

  get 'wenique/product'

  get 'wenique/contact'

  get 'wenique/checkout'

  get 'wenique/categories'

  
  get 'wenique/registers_new'
  
  
  get 'wenique/assign_order/new' => 'wenique#assign_order_new' #지정주문제작서 작성 화면
  
  post 'wenique/assign_order/create' => 'wenique#assign_order_create', as: 'assign_order_create'
  
  get 'wenique/assign_order/show/:id' => 'wenique#assign_order_show' #지정주문제작서 확인
  
  get 'wenique/assign_order/edit/:id' => 'wenique#assign_order_edit'
  
  patch 'wenique/assign_order/update/:id' => 'wenique#assign_order_update', as: 'assign_order_update'
  
  post 'assign_order/:id/create' => 'wenique#assign_order_comment_create', as: 'assign_order_comment_create'
  
  get 'assign_order/:id/make_price' => 'wenique#assign_order_make_price', as: 'assign_order_make_price'
  
  post 'assign_order/:id/make_price/create' => 'wenique#assign_order_make_price_create', as: 'price_create'
  
  get 'assign_order/:id/price_agree' => 'wenique#price_agree'
  
  get '/users/search' => 'wenique#user_search', as: 'search_users'
  
  get 'wenique/unassign_order'  #미지정주문제작 화면
  
  get 'wenique/handicrafts'
  
  get '/mypage/assign_order/show/:id' => 'wenique#assign_order_show'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :categories
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :following
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  belongs_to :autority
  
  has_one :seller_page
  has_many :unassign_requests, dependent: :destroy
  has_many :assign_request_comments, dependent: :destroy

  has_many :orders, dependent: :nullify
  
  has_many :goods, through: :carts
  has_many :carts, dependent: :destroy  
  
  def following?(other_user)
    active_relationships.find_by(following_id: other_user.id)
  end
  
  def follow!(other_user)
    active_relationships.create!(following_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end
  
  
end

app/controllers/wenique_controller.rb
class WeniqueController < ApplicationController
  before_action :require_login, only: [:assign_order_new, :assign_order_show]
  
  def index
    #수공업자 권한부여
    users = User.all
    users.each do |u|
      if u.authorization != '1' && u.business_number != nil
        u.authorization = '2'
        u.save
      end
    end
  end


  def product
    @goods = Good.all
  end

  def contact
  end

  def checkout
  end

  def categories
  end

  def cart
  end
  
  def assign_order_new
    @categories = Category.all
    @order = AssignRequest.new
    @sellers = User.where(authorization: 2).order(:name)
    
  end
  
  def assign_order_create
    @order = AssignRequest.new(order_params)
    @order.content = params[:assign_request][:content]
    @order.c_id = current_user.id
    @order.s_id = params[:assign_request][:s_id]
    @order.g_private = params[:assign_request][:g_private]
    
    categories = params[:assign_request][:category_ids].split(',')
    categories.each do |c|
      @order.category_ids << c
    end
    @order.save
    
    PriceComfirm.new(request_id: @order.id).save
    
    redirect_to "/wenique/assign_order/show/#{@order.id}"
  end
  
  def assign_order_show
    @order = AssignRequest.find(params[:id])
    @comment = AssignRequestComment.new
    @order_comments = AssignRequestComment.where(request_id: @order.id)
    @current_user_autority = current_user.id
    @price_check_status = PriceComfirm.where(request_id: @order.id).first

  end
  
  def assign_order_edit
    @order = AssignRequest.find(params[:id])
    @categories = Category.all

  end
  
  def assign_order_update
    @order = AssignRequest.find(params[:id])
    @order.content = params[:assign_request][:content]
    @order.c_id = current_user.id
    @order.g_private = params[:assign_request][:g_private]
    @order.categories.clear
    cate = params[:assign_request][:category_ids].split(',')
    cate.each do |c|
      @order.category_ids = c
    end
    
    unless params[:assign_request][:img_url] == nil
      @order.img_url = params[:assign_request][:img_url]
    end

    @order.save
    
    redirect_to "/wenique/assign_order/show/#{@order.id}"
  end
  
  def assign_order_comment_create
    @order = AssignRequest.find(params[:id])
    @comment = AssignRequestComment.new
    @comment.content = params[:assign_request_comment][:content]
    @comment.u_id = current_user.id
    @comment.request_id = @order.id
    @comment.save
    
    redirect_to "/wenique/assign_order/show/#{@order.id}"
  end
  
  def assign_order_make_price
    @price = PriceComfirm.where(request_id: params[:id]).first

  end
  
  def assign_order_make_price_create
    @order = AssignRequest.find(params[:id])
    @price = PriceComfirm.where(request_id: @order.id).first
    @price.price = params[:price_comfirm][:price]
    @order.s_id = current_user.id
    @order.save
    @price.save
    
    redirect_to "/wenique/assign_order/show/#{@order.id}"
  end
  
  def price_agree
    @order = AssignRequest.find(params[:id])
    @price = PriceComfirm.where(request_id: @order.id).first
    @price.c_check = 1
    @price.save
    @goods = Good.new()
    
    redirect_to "/wenique/assign_order/show/#{@order.id}"
  end
  
  def user_search
    # @seller = Users.where(authorization = '2')
    @users = Users.search do
      keywords params[:query]
    end.results
  
    respond_to do |format|
      format.html { render :action => "assign_order_new" }
      format.xml  { render :xml => @users }
  end
  
  redirect_to :back
  end
  
  def unassign_order
  end
  
  def handicrafts
    @user = User.all
    @order = AssignRequest.all
  end
  
private
    def order_params
      params.require(:assign_request).permit(:content, :s_id, :g_private_value, :img_url, category_ids: [])
    end
    
    def require_login
      unless user_signed_in?
      redirect_to '/users/sign_in'
      end
    end
  
  
end

app/helpers/wenique_helper.rb
module WeniqueHelper
end

app/views/wenique/assign_order_edit.html.erb
 <link rel="stylesheet" type="text/css" href="order.css">
<%= form_for(@order, url: assign_order_update_path, method: 'patch', :multipart => true, :class => "order") do |f| %>
<%= f.label :content, '주문 요청 내용' %><br>
<%= f.text_area :content,{:class => "order_textarea"} %></br>

<%= f.label :g_private, '완성제품 공개여부' %>
<%= f.check_box :g_private %><p>주문 제작 완료후 상품 공개&판매를 원하시면 체크해주세요</p></br>

<%= f.label :category_id, '카테고리' %>
<% @categories.each do |c| %>
<%= f.check_box :category_ids, { multiple: true }, c.id, false %>
<%= c.name %>
<% end %></br>

<%= f.label :img_url,'디자인 이미지' %>
<%= f.file_field :img_url %>
<br>

<%= f.submit '작성', :class => "button"%>
<% end %>

app/views/wenique/assign_order_make_price.html.erb
  <link rel="stylesheet" type="text/css" href="order.css">
 <container class="makeprice">
 <%= form_for(@price, url: price_create_path, method: 'post') do |f| %>
           
          <%= f.label :price, '가격' %>
          <%= f.text_field :price %></br>
          <%= f.submit '확정', :class => 'button'%>
  <% end %>
  </container>

app/views/wenique/assign_order_new.html.erb
 <link rel="stylesheet" type="text/css" href="order.css">
  
<%= form_for(@order, url: assign_order_create_path, method: 'post', :multipart => true, :class => "order") do |f| %>

<%= f.label :content, '주문 요청 내용' %><br>
<%= f.text_area :content , {:class => "order_textarea"}%></br>

<%= f.label :s_id, '수공업자 지정'%>
<%= f.collection_select :s_id, @sellers, :id, :name, include_blank: true %><br>


<%= f.label :g_private, '완성제품 공개여부' %>
<%= f.check_box :g_private %><p>주문 제작 완료후 상품 공개&판매를 원하시면 체크해주세요</p></br>

<%= f.label :category_id, '카테고리' %>
<% @categories.each do |c| %>
<%= f.check_box :category_ids, { multiple: true, :id => "catecheck" }, c.id, false %>
<%= c.name %>
<% end %></br>

<%= f.label :img_url, '디자인 이미지' %>
<%= f.file_field :img_url %>
<br>

<%= f.submit '작성', :onclick => "validateCheckbox();", :class => "button"%>
<% end %>

app/views/wenique/assign_order_show.html.erb
 <link rel="stylesheet" type="text/css" href="order.css">
<container class="ordershow">
<p>
  <strong>주문 요청 내용</strong><br>
  <%= @order.content %>
</p>

<p>
  <strong>카테고리</strong><br>
  <% @order.categories.each do |c| %>
  <%= c.name %>
  <% end %>
</p>

<p>
<strong>디자인 이미지</strong><br>
  <%= image_tag("#{@order.img_url}",class:"orderimg")%>
</p>

<br>
<button class="button">
<%= link_to 'Edit', "/wenique/assign_order/edit/#{@order.id}" %>
</button><br>

<hr>

<br>
 <div class="inline fields">
  <%= form_for(@comment, url: assign_order_comment_create_path, method: 'post') do |f| %>
  <%= f.label :content, '가격 협상 댓글' %><br>
  <div class="field">
  <%= f.text_area :content,{:class => "order_comment", :placeholder =>"댓글에서 가격 및 제작 요건에 대해 협의해주세요"} %>
  <%= f.submit '작성', :class => 'comment_button'%>
  </div>
<% end %>
</div>
<hr>

<br>
<% @order_comments.each do |c| %>
댓글: <%= c.content %> <%= c.created_at.strftime("%Y-%m-%d  %H:%M:%S") %></br><br>
<% end %>
<% unless @order_comments == [] %>
  <hr>
<% end %>

<br>
<% if @current_user_autority == @order.s_id %> 
    <% if @price_check_status.price == nil %>
      <%= link_to '가격확정하기', assign_order_make_price_path, class: "btn" %>
    <% elsif %>
      <p><%= @price_check_status.price %></p>
      <% if @price_check_status.c_check == 1%>
            <p class="btn"> 가격 협상 완료</p>
      <% end%>
    <% end %>
<% elsif @current_user_autority == @order.c_id%>
   <% if @price_check_status.price == nil %>
      <p class='btn'>가격 미정</p>
    <% elsif %>
      <p><%= @price_check_status.price %>원</p>
      <% if @price_check_status.c_check == 0 %>
      <button><%= link_to '정해진 가격 동의', "/assign_order/#{@order.id}/price_agree" %></button>
      <% else %>
      <p class="btn"> 가격 협상 완료</p>
      <% end %>
    <% end %>
<% end %>

</container>

app/views/wenique/categories.html.erb
<h1>Wenique#categories</h1>
<p>Find me in app/views/wenique/categories.html.erb</p>

app/views/wenique/checkout.html.erb
<h1>Wenique#checkout</h1>
<p>Find me in app/views/wenique/checkout.html.erb</p>

app/views/wenique/contact.html.erb
<h1>Wenique#contact</h1>
<p>Find me in app/views/wenique/contact.html.erb</p>

app/views/wenique/handicrafts.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">이름</th>
        <th scope="col">의뢰요청 받은횟수</th>
      </tr>
    </thead>
    <tbody>
      <% @i = 1 %>
      <% @user.each do |u| %>
          <% if u.authorization == '2' %>
              <% @a = 0 %>
              <tr>
                <th scope="row"><%= @i %></th>
                <td><%= u.name %></td>
                <td>
                    <% @order.each do |e| %>
                        <% if u.id == e.s_id %>
                            <% @a = @a + 1 %>
                        <% end %>
                    <% end %>
                    <%= @a %>
                </td>
              </tr>
              <% @i = @i + 1 %>
          <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/wenique/index.html.erb
	<!-- Home -->

	<div class="home">
		
		<!-- Home Slider -->

		<div class="home_slider_container">
			<div class="owl-carousel owl-theme home_slider">
				
				<!-- Home Slider Item -->
				<div class="owl-item">
					<div class="home_slider_background" style="background-image:url(/assets/sample_img.png)"></div>
					<div class="home_slider_content">
						<div class="home_slider_content_inner">
							<!--<div class="home_slider_subtitle">Promo Prices</div>-->
							<!--<div class="home_slider_title">New Collection</div>-->
						</div>	
					</div>
				</div>

				<!-- Home Slider Item -->
				<div class="owl-item">
					<div class="home_slider_background" style="background-image:url(/assets/sample_img.png)"></div>
					<div class="home_slider_content">
						<div class="home_slider_content_inner">
							<!--<div class="home_slider_subtitle">Promo Prices</div>-->
							<!--<div class="home_slider_title">New Collection</div>-->
						</div>	
					</div>
				</div>

				<!-- Home Slider Item -->
				<div class="owl-item">
					<div class="home_slider_background" style="background-image:url(/assets/sample_img.png)"></div>
					<div class="home_slider_content">
						<div class="home_slider_content_inner">
							<!--<div class="home_slider_subtitle">Promo Prices</div>-->
							<!--<div class="home_slider_title">New Collection</div>-->
						</div>	
					</div>
				</div>

			</div>
			
			<!-- Home Slider Nav -->

			<div class="home_slider_next d-flex flex-column align-items-center justify-content-center"><img src="/assets/arrow_r.png" alt=""></div>

			<!-- Home Slider Dots -->

			<div class="home_slider_dots_container">
				<div class="container">
					<div class="row">
						<div class="col">
							<div class="home_slider_dots">
								<ul id="home_slider_custom_dots" class="home_slider_custom_dots">
									<li class="home_slider_custom_dot active">01.<div></div></li>
									<li class="home_slider_custom_dot">02.<div></div></li>
									<li class="home_slider_custom_dot">03.<div></div></li>
								</ul>
							</div>
						</div>
					</div>
				</div>		
			</div>
		</div>
	</div>
	
	
	<!-- Promo -->

	<div class="promo">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title_container text-center">
						<div class="section_subtitle">best product</div><br>
						<!--<div class="section_title">promo prices</div>-->
					</div>
				</div>
			</div>
			<div class="row promo_container">

				<!-- Promo Item -->
				<div class="col-lg-4 promo_col">
					<div class="promo_item">
						<div class="promo_image">
							<img src="/assets/가구-1.jpg" alt="">
							<div class="promo_content promo_content_1">
								<div class="promo_title"><!---30% off--></div>
								<div class="promo_subtitle"><!--on all bags--></div>
							</div>
						</div>
						<div class="promo_link"><a href="#">Shop Now</a></div>
					</div>
				</div>

				<!-- Promo Item -->
				<div class="col-lg-4 promo_col">
					<div class="promo_item">
						<div class="promo_image">
							<img src="/assets/가방-1.jpg" alt="">
							<div class="promo_content promo_content_2">
								<div class="promo_title"><!---30% off--></div>
								<div class="promo_subtitle"><!--coats & jackets--></div>
							</div>
						</div>
						<div class="promo_link"><a href="#">Shop Now</a></div>
					</div>
				</div>

				<!-- Promo Item -->
				<div class="col-lg-4 promo_col">
					<div class="promo_item">
						<div class="promo_image">
							<img src="/assets/액세사리-1.jpg" alt="">
							<div class="promo_content promo_content_3">
								<div class="promo_title"><!---25% off--></div>
								<div class="promo_subtitle"><!--on Sandals--></div>
							</div>
						</div>
						<div class="promo_link"><a href="#">Shop Now</a></div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<!-- New Arrivals -->

	<div class="arrivals">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="section_title_container text-center">
						<div class="section_subtitle">best product</div><br>
						<!--<div class="section_title">새로 나온 인기있는 디자인</div>-->
					</div>
				</div>
			</div>
			<div class="row products_container">

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/가구-2.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">화분 받침 가구</a></div>
								<div class="product_price">$45.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/가방-2.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">고급 가죽 가방</a></div>
								<div class="product_price">$35.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/가죽-1.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">가죽 핸드폰 파우치</a></div>
								<div class="product_price">$145.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

			</div>
			<!-- 두번째 줄 -->
			<div class="row products_container">

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/가방-3.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">초대형 사첼백</a></div>
								<div class="product_price">$45.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/액세사리-2.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">리본 귀걸이</a></div>
								<div class="product_price">$35.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/핸드폰케이스-1.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">캔퍼스 핸드폰 케이스</a></div>
								<div class="product_price">$145.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="row products_container">

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/액세사리-3.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">퍼즐 목걸이</a></div>
								<div class="product_price">$45.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/핸드폰케이스-2" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">럭셔리 핸드폰 케이스</a></div>
								<div class="product_price">$35.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

				<!-- Product -->
				<div class="col-lg-4 product_col">
					<div class="product">
						<div class="product_image">
							<img src="/assets/가죽-2.jpg" alt="">
						</div>
						<div class="rating rating_4">
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
							<i class="fa fa-star"></i>
						</div>
						<div class="product_content clearfix">
							<div class="product_info">
								<div class="product_name"><a href="product.html">검은 가죽 지갑</a></div>
								<div class="product_price">$145.00</div>
							</div>
							<div class="product_options">
								<div class="product_buy product_option"><img src="/assets/shopping-bag-white.svg" alt=""></div>
								<div class="product_fav product_option">+</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<!-- Gallery -->

	<div class="gallery">
		<div class="gallery_image" style="background-image:url(images/gallery.jpg)"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="gallery_title text-center">
						<ul>
							<li><a href="#">#wenique</a></li>
							<li><a href="#">#wenique_hinstagram</a></li>
							<li><a href="#">#특별한 제작</a></li>
						</ul>
					</div>
					<div class="gallery_text text-center">*Integer ut imperdiet erat. Quisque ultricies lectus tellus, eu tristique magna pharetra.</div>
				</div>
			</div>
		</div>	
		<div class="gallery_slider_container">
			
			<!-- Gallery Slider -->
			<div class="owl-carousel owl-theme gallery_slider">
				
				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="/assets/가구-1.jpg">
						<img src="/assets/가구-1.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="/assets/가방-1.jpg">
						<img src="/assets/가방-1.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="/assets/가방-3.jpg">
						<img src="/assets/가방-3.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="/assets/액세사리-1.jpg">
						<img src="/assets/액세사리-1.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="/assets/핸드폰케이스-1.jpg">
						<img src="/assets/핸드폰케이스-1.jpg" alt="">
					</a>
				</div>

				<!-- Gallery Item -->
				<div class="owl-item gallery_item">
					<a class="colorbox" href="/assets/액세사리-3.jpg">
						<img src="/assets/액세사리-3.jpg" alt="">
					</a>
				</div>

			</div>
		</div>
	</div>

app/views/wenique/product.html.erb
<h1>Products for sale</h1>
<% @goods.each do |good| %>
	<div class="well">
		<div class="row">
			<div class="col-sm-8">
				<h3><%= good.price %></h3>
			</div>
			<div class="col-sm-4">
				<div class="pull-right">
				<%= form_tag(@cart, remote: true) do |f| %>
					
					<h5><%= good.price %></h5>
					<div class="form-group">
						
					</div>
					
				<% end %>
				</div>
			</div>
		</div>
	</div>s

app/views/wenique/registers_new.html.erb
<link rel="stylesheet" type="text/css" href="registration_new.css">
<div class="registration_new">
    <div>

        <h1>회원가입 선택</h1>
        <a href="/users/register"><button class="button gallery_button">일반사용자 회원가입</button></a><br>
        <a href="/users/seller_new"><button class="button gallery_button">수공업자 회원가입</button></a>
    </div>
</div>