config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :carts
  
  get 'mypage/mypage'
  get 'mypage/requests_list'

  resources :orders, except: [:create, :new]
  post 'orders/placeorder' => 'orders#placeorder'
  get 'allorders' => 'orders#all'
  
  get 'cart' => 'carts#index'
  delete 'cart/:id' => 'carts#deletecart'
  post 'cart/:id' => 'carts#addcart'

 resources :boards, only: [:index] do
    resources :articles, only: [:update, :destroy, :create]
  end
  
  scope '/boards/:board_id', except: [:update, :destroy, :create] do
    resources :articles
  end
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :path => "users", :path_names => {:sign_up => "register"}
  
  devise_scope :user do
    get "/users/seller_new" =>"registrations#seller_new"
    get "/users/sign_out" =>"devise/sessions#destroy"
  end
  
  
 

  root 'wenique#index'

  get 'wenique/product'

  get 'wenique/contact'

  get 'wenique/checkout'

  get 'wenique/categories'

  
  get 'wenique/registers_new'
  
  
  get 'wenique/assign_order/new' => 'wenique#assign_order_new' #지정주문제작서 작성 화면
  
  post 'wenique/assign_order/create' => 'wenique#assign_order_create', as: 'assign_order_create'
  
  get 'wenique/assign_order/show/:id' => 'wenique#assign_order_show' #지정주문제작서 확인
  
  get 'wenique/assign_order/edit/:id' => 'wenique#assign_order_edit'
  
  patch 'wenique/assign_order/update/:id' => 'wenique#assign_order_update', as: 'assign_order_update'
  
  post 'assign_order/:id/create' => 'wenique#assign_order_comment_create', as: 'assign_order_comment_create'
  
  get 'assign_order/:id/make_price' => 'wenique#assign_order_make_price', as: 'assign_order_make_price'
  
  post 'assign_order/:id/make_price/create' => 'wenique#assign_order_make_price_create', as: 'price_create'
  
  get 'assign_order/:id/price_agree' => 'wenique#price_agree'
  
  get '/users/search' => 'wenique#user_search', as: 'search_users'
  
  get 'wenique/unassign_order'  #미지정주문제작 화면
  
  get 'wenique/handicrafts'
  
  get '/mypage/assign_order/show/:id' => 'wenique#assign_order_show'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    # attr_accessor :title, :board_id
    mount_uploader :img, ImguploaderUploader
    belongs_to :board
    
    #u_id는?
end

app/models/assign_request.rb
class AssignRequest < ActiveRecord::Base
    has_and_belongs_to_many :categories
    has_one :good
    has_many :assign_request_comments, dependent: :destroy #혜민이한테 물어보기
    
    mount_uploader :img_url, ImguploaderUploader
    # validates :category_ids, acceptance: true
    # validates_acceptance_of :category_ids, message: 'tick the checkbox!'
    


    
    # , :join_table => "assign_requests_categories", :foreign_key => "assign_request_id"
end

app/models/autority.rb
class Autority < ActiveRecord::Base
    has_many :users, dependent: :destroy
end

app/models/board.rb
class Board < ActiveRecord::Base
        has_many :articles, dependent: :destroy
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :good
    
    def goodz
        @good = Good.find(self.good_id)
        return @good
    end
    
 
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :assign_requests
    has_and_belongs_to_many :users
    has_and_belongs_to_many :unassign_requets
end

app/models/good.rb
class Good < ActiveRecord::Base
    belongs_to :assign_request
    belongs_to :unassign_request
    has_one :request_status
    has_one :portfolio
    has_many :reviews, dependent: :destroy
    has_many :order_items
    
    has_many :carts
    has_many :Users, through: :Carts
    
    has_many :itemorder
    has_many :orders, through: :goodorder    
end

app/models/goodorder.rb
class Goodorder < ActiveRecord::Base
  belongs_to :good
  belongs_to :order
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    
    has_many :goodorders, dependent: :destroy
    has_many :items, through: :goodorders
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    belongs_to :good
end

app/models/price_comfirm.rb
class PriceComfirm < ActiveRecord::Base
    # belongs_to :assign_request
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :following, class_name: "User", foreign_key: :following_id, primary_key: :id
    validates :following_id, presence: true
    belongs_to :follower, class_name: "User"
    validates :follower_id, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :good
end

app/models/seller_page.rb
class SellerPage < ActiveRecord::Base
    belongs_to :user
    
    #포트폴리오는 ?
end

app/models/status.rb
class Status < ActiveRecord::Base
    has_many :request_statues, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :categories
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :following
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  belongs_to :autority
  
  has_one :seller_page
  has_many :unassign_requests, dependent: :destroy
  has_many :assign_request_comments, dependent: :destroy

  has_many :orders, dependent: :nullify
  
  has_many :goods, through: :carts
  has_many :carts, dependent: :destroy  
  
  def following?(other_user)
    active_relationships.find_by(following_id: other_user.id)
  end
  
  def follow!(other_user)
    active_relationships.create!(following_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end
  
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  # before_action :areyouadmin, only: [:edit, :update, :create ]

  # GET /items
  # GET /items.json
  def index
    @items = Good.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end
  
  

  # POST /items
  # POST /items.json
  def create
    @item = Good.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:good).permit(:price,:image_url)
    end
    
    # def areyouadmin
    # if !current_user.try(:isadmin)
    #   redirect_to root_url
    # end
    # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.file_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>
<div id="item_collection">
    <% @items.each do |good| %>

        <a href="<%= root_url + "items/" + good.id.to_s %>">
          <div id="item">
            <%= image_tag(good.image_url)%>
            <%= good.price %>
            <% if current_user.try(:isadmin?) %>
              <%= link_to 'Edit', edit_item_path(item) %>
            <% end %>
            
          </div>
        </a>



    <% end %>
  
</div>


<br>
<% if current_user.try(:isadmin?) %>
  <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag root_url + "cart/" + @item.id.to_s do %>

  <div class="field">
    <%= link_to image_tag(@item.image_url), @item.image_url %>
    <%= print @item.image_url %>
  </div>
  

  <div class="field">
    <strong>Price:</strong>
  <%= @item.price %>
  </div>
  <div class="field">
    <strong>Quantity </strong>
    <%= number_field_tag :quantity,'1', min: 1 %>
  </div>
  
  <div class="actions">
    <%= submit_tag "Add To Cart"%>
  </div>
<% end %>


<% if current_user.try(:isadmin?) %>
<%= link_to 'Edit', edit_item_path(@item) %> |
<% end %>
<%= link_to 'Back', items_path %>