config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :carts
  
  get 'mypage/mypage'
  get 'mypage/requests_list'

  resources :orders, except: [:create, :new]
  post 'orders/placeorder' => 'orders#placeorder'
  get 'allorders' => 'orders#all'
  
  get 'cart' => 'carts#index'
  delete 'cart/:id' => 'carts#deletecart'
  post 'cart/:id' => 'carts#addcart'

 resources :boards, only: [:index] do
    resources :articles, only: [:update, :destroy, :create]
  end
  
  scope '/boards/:board_id', except: [:update, :destroy, :create] do
    resources :articles
  end
  
  devise_for :users, :controllers => { :registrations => "registrations" }, :path => "users", :path_names => {:sign_up => "register"}
  
  devise_scope :user do
    get "/users/seller_new" =>"registrations#seller_new"
    get "/users/sign_out" =>"devise/sessions#destroy"
  end
  
  
 

  root 'wenique#index'

  get 'wenique/product'

  get 'wenique/contact'

  get 'wenique/checkout'

  get 'wenique/categories'

  
  get 'wenique/registers_new'
  
  
  get 'wenique/assign_order/new' => 'wenique#assign_order_new' #지정주문제작서 작성 화면
  
  post 'wenique/assign_order/create' => 'wenique#assign_order_create', as: 'assign_order_create'
  
  get 'wenique/assign_order/show/:id' => 'wenique#assign_order_show' #지정주문제작서 확인
  
  get 'wenique/assign_order/edit/:id' => 'wenique#assign_order_edit'
  
  patch 'wenique/assign_order/update/:id' => 'wenique#assign_order_update', as: 'assign_order_update'
  
  post 'assign_order/:id/create' => 'wenique#assign_order_comment_create', as: 'assign_order_comment_create'
  
  get 'assign_order/:id/make_price' => 'wenique#assign_order_make_price', as: 'assign_order_make_price'
  
  post 'assign_order/:id/make_price/create' => 'wenique#assign_order_make_price_create', as: 'price_create'
  
  get 'assign_order/:id/price_agree' => 'wenique#price_agree'
  
  get '/users/search' => 'wenique#user_search', as: 'search_users'
  
  get 'wenique/unassign_order'  #미지정주문제작 화면
  
  get 'wenique/handicrafts'
  
  get '/mypage/assign_order/show/:id' => 'wenique#assign_order_show'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    # attr_accessor :title, :board_id
    mount_uploader :img, ImguploaderUploader
    belongs_to :board
    
    #u_id는?
end

app/models/autority.rb
class Autority < ActiveRecord::Base
    has_many :users, dependent: :destroy
end

app/models/board.rb
class Board < ActiveRecord::Base
        has_many :articles, dependent: :destroy
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    
    belongs_to :user
    belongs_to :good
    
    def goodz
        @good = Good.find(self.good_id)
        return @good
    end
    
 
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :assign_requests
    has_and_belongs_to_many :users
    has_and_belongs_to_many :unassign_requets
end

app/models/good.rb
class Good < ActiveRecord::Base
    belongs_to :assign_request
    belongs_to :unassign_request
    has_one :request_status
    has_one :portfolio
    has_many :reviews, dependent: :destroy
    has_many :order_items
    
    has_many :carts
    has_many :Users, through: :Carts
    
    has_many :itemorder
    has_many :orders, through: :goodorder    
end

app/models/goodorder.rb
class Goodorder < ActiveRecord::Base
  belongs_to :good
  belongs_to :order
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    
    has_many :goodorders, dependent: :destroy
    has_many :items, through: :goodorders
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
    belongs_to :good
end

app/models/price_comfirm.rb
class PriceComfirm < ActiveRecord::Base
    # belongs_to :assign_request
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :following, class_name: "User", foreign_key: :following_id, primary_key: :id
    validates :following_id, presence: true
    belongs_to :follower, class_name: "User"
    validates :follower_id, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :good
end

app/models/seller_page.rb
class SellerPage < ActiveRecord::Base
    belongs_to :user
    
    #포트폴리오는 ?
end

app/models/status.rb
class Status < ActiveRecord::Base
    has_many :request_statues, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :categories
  has_many :active_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :following
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  belongs_to :autority
  
  has_one :seller_page
  has_many :unassign_requests, dependent: :destroy
  has_many :assign_request_comments, dependent: :destroy

  has_many :orders, dependent: :nullify
  
  has_many :goods, through: :carts
  has_many :carts, dependent: :destroy  
  
  def following?(other_user)
    active_relationships.find_by(following_id: other_user.id)
  end
  
  def follow!(other_user)
    active_relationships.create!(following_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end
  
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wenique</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" type="text/css" href="bootstrap.css">
  <link href="font-awesome.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="owl.carousel.css">
  <link rel="stylesheet" type="text/css" href="owl.theme.default.css">
  <link rel="stylesheet" type="text/css" href="animate.css">
  <link href="colorbox.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="main_styles.css">
  <link rel="stylesheet" type="text/css" href="responsive.css">
  <link rel="stylesheet" type="text/css" href="font-awesome.css">  

  <!--<link rel="stylesheet" type="text/css" href="assets/bootstrap.css">-->
  <!--<link href="assets/font-awesome.css" rel="stylesheet" type="text/css">-->
  <!--<link rel="stylesheet" type="text/css" href="assets/owl.carousel.css">-->
  <!--<link rel="stylesheet" type="text/css" href="assets/owl.theme.default.css">-->
  <!--<link rel="stylesheet" type="text/css" href="assets/animate.css">-->
  <!--<link href="assets/colorbox.css" rel="stylesheet" type="text/css">-->
  <!--<link rel="stylesheet" type="text/css" href="assets/main_styles.css">-->
  <!--<link rel="stylesheet" type="text/css" href="assets/responsive.css">-->

  
</head>
<body>

	
	<!-- Header -->

	<header class="header">
		<div class="header_inner d-flex flex-row align-items-center justify-content-start">
			<div class="logo"><a href="/"><img src="/assets/logo_2.png" height="80"></a></div>
			<nav class="main_nav">
				<ul>
					<!--<li><a href="/">home</a></li>-->
					<% if user_signed_in? %>
						<li><%= link_to "product", items_path %></li> <!-- 판매제품 -->
					<% else %>
						<li><a href="/users/sign_in">product</a></li>
					<% end %>
					<li class="dropdown"><a href="/wenique/assign_order/new">order</a>
					<!--<i class="icon-angle-down"></i>-->
						<ul class="dropdown-menu">
                        	<li><a href="/wenique/assign_order/new">수공업자 지정 주문</a></li>
                        	<li><a href="/wenique/unassign_order/new">수공업자 미지정 주문</a></li>
                        	<li><a href="#">주문 제작 확인</a></li>	
                        </ul>
					</li><!-- 주문제작 -->
					<li><a href="/wenique/handicrafts">handicrafts</a></li><!-- 수공업자 -->
					<li><a href="/boards/2/articles">notice</a></li><!-- 공지사항 -->
				</ul>
			</nav>
			<div class="header_content ml-auto">
				<div class="search header_search">
					<form action="#">
						<input type="search" class="search_input" required="required">
						<button type="submit" id="search_button" class="search_button"><img src="/assets/magnifying-glass.svg" alt=""></button>
					</form>
				</div>
				<div class="shopping">
					<!-- Cart -->
						<% if user_signed_in? %>
							<span class="cart">
								<%= link_to "MY CART", carts_path %> | 
							</span>
						<% else %>
							<span class="cart">
								<a href="/users/sign_in">MY CART</a> | 
							</span>
						<% end %>
					<!-- Star -->
					<!--<a href="#">-->
					<!--	<div class="star">-->
					<!--		<img src="images/star.svg" alt="">-->
					<!--		<div class="star_num_container">-->
					<!--			<div class="star_num_inner">-->
					<!--				<div class="star_num">0</div>-->
					<!--			</div>-->
					<!--		</div>-->
					<!--	</div>-->
					<!--</a>-->
					<!--로그인-->
				      <% if current_user == nil %>
				  		<a href="/users/sign_in">LOG IN</a> |
				  		<a href="/wenique/registers_new">SIGN UP</a>
				        
				      <% else %>
				  		<a href="/users/sign_out"> LOG OUT</a> |
				  		<a href="/mypage/requests_list"><img src="/assets/mypage.png" height="17"> MY PAGE</a>
				      <% end %>
				
		
					<!-- Avatar -->
					<!--<a href="#">-->
					<!--	<div class="avatar">-->
					<!--		<img src="images/avatar.svg" alt="">-->
					<!--	</div>-->
					<!--</a>-->
				</div>
			</div>

			<div class="burger_container d-flex flex-column align-items-center justify-content-around menu_mm"><div></div><div></div><div></div></div>
		</div>
	</header>  


	<!-- Menu -->

	<div class="menu d-flex flex-column align-items-end justify-content-start text-right menu_mm trans_400">
		<div class="menu_close_container"><div class="menu_close"><div></div><div></div></div></div>
		<div class="logo menu_mm"><a href="#">wenique</a></div>
		<div class="search">
			<form action="#">
				<input type="search" class="search_input menu_mm" required="required">
				<button type="submit" id="search_button_menu" class="search_button menu_mm"><img class="menu_mm" src="/assets/magnifying-glass.svg" alt=""></button>
			</form>
		</div>
		<nav class="menu_nav">
			<ul class="menu_mm">
					<li class="menu_mm"><a href="/">home</a></li>
					<li class="menu_mm"><a href="/wenique/product">product</a></li> <!-- 판매제품 -->
					<li class="menu_mm"><a href="/wenique/assign_order/new">order</a></li><!-- 주문제작 -->
					<li class="menu_mm"><a href="/wenique/handicrafts">handicrafts</a></li><!-- 수공업자 -->
					<li class="menu_mm"><a href="/boards/2/articles">notice</a></li><!-- 공지사항 -->
			</ul>
		</nav>
	</div>

	<div class="super_container">
		<%= yield %>
		<%= javascript_include_tag 'application' %>
		<%= stylesheet_link_tag    'application' %>


	</div>

    <footer>
    	<div></div>
 			<div>
 				<div class="footer_div">
 					<div></div>
 					<div><a href="#"><p	id="footer_p">HOME</p></a></div>
 					<div><a href="#"><p	id="footer_p">PRODUCT</p></a></div>
 					<div><a href="#"><p	id="footer_p">ORDER</p></a></div>
 					<div><a href="#"><p	id="footer_p">HANDICRAFT</p></a></div>
 					<div><a href="#"><p	id="footer_p">NOTICE</p></a></div>
 					<div></div>
 				</div>
 				<div class="footer_con">
 					<p>사업자번호 : 000000000000</p>
 					<p>팀원 : 김승래, 이혜민, 한현수, 박결</p>
 					<p>주소 : 서울특별시 구로구 항동 1번지</p>
 					<p>Copyright &COPY; Wenique.ltd</p>
 				</div>
 			</div>
 			<div></div>
    </footer>


<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>-->
<script src="//d1p7wdleee1q2z.cloudfront.net/post/search.min.js"></script>
<script src="assets/jquery-3.2.1.min.js"></script>
<script src="assets/popper.js"></script>
<script src="assets/bootstrap.js"></script>
<script src="assets/owl.carousel.js"></script>
<script src="assets/easing.js"></script>
<script src="assets/parallax.min.js"></script>
<script src="assets/jquery.colorbox-min.js"></script>
<script src="assets/custom.js"></script>



</body>
</html>